Web/Areas/Admin/Models/Sales/SaleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Areas.Admin.Models.Sales
{
    public class SaleViewModel
    {
        public int Id { get; set; } = 0;
        [Required]
        public int Count { get; set; } = 0;
        [Required]
        public int ClientId { get; set; } = 0;
        [Required]
        public int ProductId { get; set; } = 0;
        public string ClientName { get; set; } = "";
        public string ProductName { get; set; } = "";
    }
}

Web/Areas/Admin/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.DTO.Clients;
using ApplicationCore.Interfaces;
using ApplicationCore.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Areas.Admin.Models.Clients;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class ClientsController : Controller
    {
        private readonly IClientsService _clients;
        private readonly IMapper _mapper;

        public ClientsController(IClientsService clients, IMapper mapper)
        {
            _clients = clients;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _clients.GetClientRoles();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> GetClients()
        {
            var parameters = AjaxParametersFactory.GetDataTableParameters(Request);
            var result = await _clients.GetClientsAsync(parameters);
            return Json(new
            {
                result.Draw,
                result.RecordsTotal,
                result.RecordsFiltered,
                result.Data,
                result.Error
            });
        }

        [HttpPost]
        public async Task<IActionResult> EditClient(ClientViewModel model)
        {
            var result = false;
            var message = "";

            if (ModelState.IsValid)
            {
                var client = _mapper.Map<ClientViewModel, ClientDTO>(model);

                var res = await _clients.EditClientAsync(client);

                result = res.Data;
                message = res.Message;
            }
            else
            {
                message = "Client not saved. Enter correct data";
            }

            return Json(new
            {
                result,
                message
            });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteClient(int id)
        {
            var result = false;
            var message = "";

            if (ModelState.IsValid)
            {
                var res = await _clients.DeleteClientAsync(id);

                result = res.Data;
                message = res.Message;
            }
            else
            {
                message = "Error operation";
            }

            return Json(new
            {
                result,
                message
            });
        }

        [HttpPost]
        public async Task<IActionResult> GetClient(int id)
        {
            var item = new ClientDTO();
            var result = false;
            var message = "";

            if (ModelState.IsValid)
            {
                var res = await _clients.GetClientAsync(id);

                item = res.Data;
                result = res.IsSuccess;
                message = res.Message;
            }
            else
            {
                message = "Error operation";
            }

            return Json(new
            {
                result,
                item,
                message
            });
        }
    }
}

Web/Areas/Admin/Controllers/SalesController.cs
using ApplicationCore.DTO.Clients;
using ApplicationCore.DTO.Sales;
using ApplicationCore.Interfaces;
using ApplicationCore.Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Web.Areas.Admin.Models.Clients;
using Web.Areas.Admin.Models.Sales;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SalesController : Controller
    {
        private readonly ISalesService _sales;
        private readonly IClientsService _clients;
        private readonly IMapper _mapper;

        public SalesController(ISalesService sales, IClientsService clients, IMapper mapper)
        {
            _sales = sales;
            _clients = clients;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(int clientId)
        {
            var client = await _clients.GetClientAsync(clientId);

            var vm = _mapper.Map(client.Data, typeof(ClientDTO), typeof(ClientViewModel));

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> EditSale(SaleViewModel model)
        {
            var result = false;
            var message = "";

            if (ModelState.IsValid)
            {
                var sale = _mapper.Map<SaleViewModel, SaleDTO>(model);

                var res = await _sales.EditSaleAsync(sale);

                result = res.Data;
                message = res.Message;
            }
            else
            {
                message = "Enter correct data";
            }

            return Json(new
            {
                result,
                message
            });
        }

        [HttpPost]
        public async Task<IActionResult> GetSales()
        {
            var parameters = AjaxParametersFactory.GetDataTableParameters(Request);
            var result = await _sales.GetSalesAsync(parameters);
            return Json(new
            {
                result.Draw,
                result.RecordsTotal,
                result.RecordsFiltered,
                result.Data,
                result.Error
            });
        }

        [HttpPost]
        public async Task<IActionResult> GetSale(int id)
        {
            var item = new SaleDTO();
            var result = false;
            var message = "";

            if (ModelState.IsValid)
            {
                var res = await _sales.GetSaleAsync(id);

                item = res.Data;
                result = res.IsSuccess;
                message = res.Message;
            }
            else
            {
                message = "Error operation";
            }

            return Json(new
            {
                result,
                item,
                message
            });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSale(int id)
        {
            var result = false;
            var message = "";

            if (ModelState.IsValid)
            {
                var res = await _sales.DeleteSaleAsync(id);

                result = res.Data;
                message = res.Message;
            }
            else
            {
                message = "Error operation";
            }

            return Json(new
            {
                result,
                message
            });
        }
    }
}

Web/Areas/Admin/Views/Sales/Index.cshtml
@model Web.Areas.Admin.Models.Clients.ClientViewModel

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-area="Admin" asp-controller="Clients" asp-action="Index">Clients</a>
    </li>
    <li class="breadcrumb-item active">Sales for @Model.FullName</li>
</ol>

<div class="card mb-3">
    <div class="card-header d-flex justify-content-between">
        <span>
            <i class="far fa-check-square"></i>
            Sales
        </span>
        <button id="create-sale-btn" type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#make-purchase-modal" title="Create new sale for @Model.FullName">
            <i class='fas fa-shopping-cart' aria-hidden='true'></i>
            Create Sale
        </button>
    </div>
    <div class="card-body">
        <table class="table table-bordered w-100" id="sales-table" cellspacing="0">
            <thead class="table-primary">
                <tr>
                    <th>Id</th>
                    <th>Client</th>
                    <th>Product</th>
                    <th>Date</th>
                    <th>Count</th>
                    <th>Total</th>
                    <th>Operations</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<!-- Make a purchase modal -->
<div class="modal fade" id="make-purchase-modal" tabindex="-1" role="dialog" aria-labelledby="make-purchase-modal" aria-hidden="true">
    <form id="make-purchase-form">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create sale</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <fieldset class="bg-light pl-2 pr-2 pb-2">
                        <legend>Purchase product:</legend>
                        <input type="number" name="Id" value="0" class="d-none" />
                        <input type="number" name="ClientId" value="@Model.Id" class="d-none" />
                        <input type="number" name="ProductId" value="0" class="d-none" />
                        <input type="number" name="Price" value="0" step="any" class="d-none" />
                        <input type="text" name="ClientName" readonly class="form-control-plaintext font-weight-bold mb-2" value="@Model.FullName" title="Client name">
                        <div class="input-group">
                            <input type="text" name="ProductName" class="form-control form-control-sm" id="product-name" value="" required aria-label="Product name" aria-describedby="basic-addon2" title="Select product">
                            <div class="input-group-append">
                                <button id="clear-selection" class="btn btn-outline-secondary btn-sm" type="button" title="Clear selection"><i class="fas fa-times"></i></button>
                            </div>
                        </div>
                        <small class="d-block ml-2 mr-2 mb-3">Enter two symbols or more to find product</small>
                        <div class="d-flex justify-content-between">
                            <div class="form-group form-inline">
                                <label for="product-count" class="mr-1">Count:</label>
                                <input type="number" name="Count" class="form-control form-control-sm" id="product-count" min="1" value="1" required title="Enter count of products">
                            </div>
                            <div class="form-group form-inline">
                                <label for="total-price" class="mr-1">Total:</label>
                                <input type="number" name="TotalCost" step=0.01 class="form-control form-control-sm" id="total-price" value="0" readonly title="Total price">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Edit sale modal -->
<div class="modal fade" id="edit-sale-modal" tabindex="-1" role="dialog" aria-labelledby="edit-sale-modal" aria-hidden="true">
    <form id="edit-sale-form">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit sale</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <fieldset class="bg-light pl-2 pr-2 pb-2">
                        <legend>Edit sale data:</legend>
                        <input type="number" name="Id" value="0" class="d-none" />
                        <input type="number" name="ClientId" value="@Model.Id" class="d-none" />
                        <input type="number" name="ProductId" value="0" class="d-none" />
                        <input type="number" name="Price" value="0" step="any" class="d-none" />
                        <input type="text" name="ClientName" readonly class="form-control-plaintext font-weight-bold mb-2" value="@Model.FullName" title="Client name">
                        <input type="text" name="ProductName" readonly class="form-control form-control-sm mb-4" value="" title="Selected sale product">
                        <div class="d-flex justify-content-between">
                            <div class="form-group">
                                <label for="product-count">Count:</label>
                                <input type="number" name="Count" class="form-control form-control-sm w-100" id="product-count" min="1" value="1" required title="Enter count of products">
                            </div>
                            <div class="form-group mr-1 ml-1">
                                <label for="total-price">Available:</label>
                                <input type="number" name="ProductCount" class="form-control form-control-sm w-100" id="available-count" value="0" readonly title="Available product count">
                            </div>
                            <div class="form-group">
                                <label for="total-price">Total:</label>
                                <input type="number" name="TotalCost" step=0.01 class="form-control form-control-sm w-100" id="total-price" value="0" readonly title="Total price">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </form>
</div>

@section js{
    <script id="sale-operation-buttons" type="text/x-jsrender">
        <div class="d-flex justify-content-around">
            <button title="Edit sale"
                    class='btn btn-outline-success btn-sm edit-sale'
                    data-sale-id='{{:id}}'>
                <i class='far fa-edit' aria-hidden='true'></i>
            </button>
            <button title="Delete sale"
                    class='btn btn-outline-secondary btn-sm delete-sale'
                    data-sale-id='{{:id}}'
                    data-client-name='{{:clientName}}'
                    data-product-id='{{:productId}}'
                    data-product-name='{{:productName}}'>
                <i class="fas fa-times"></i>
            </button>
        </div>
    </script>

    <script>
        $(function () {
            var clientID = @Model.Id;
            crm.sales.init(clientID);
        });
    </script>
}